### ISSUE TITLE
کرش کردن اپ

### ISSUE THREAD

**Issue by mhmmdyldi** [pusheco/b4a-sample#1]
با گذاشتن کد زیر در منیفست:
CreateResourceFromFile(Macro, Pushe.Standalone)

اپ کرش میکند که دلیلش رو من پیدا نکردم. با حذف این خط کد برنامه بدون کرش اجرا میشود ولی در پنل پوشه در لیست نصب ها نمایش داده نمی شود.
این در حالی است که اپی که تست میکنم نمونه کد پروژه پوشه میباشد که در گیت هاب قرار داده است و  تمامی مراحل نصب و راه اندازی را درست دنبال میکنم

**Comment by mahdi-malv** [comment]
<div dir='rtl'>

سلام
لطفا خطای کرش رو به سوالتون ضمیمه کنید.

</div>

**Comment by mahdi-malv** [comment]
Inactive for 3 days. Feel free to reopen the issue if the problem still exists.
