### ISSUE TITLE
بازکردن اکتیویتی خاص

### ISSUE THREAD

**Issue by mahami064** [pusheco/b4a-sample#2]
![1](https://user-images.githubusercontent.com/55809870/65632056-a75e7100-dfe5-11e9-8c32-2c0adcc8ea51.JPG)
من م یخواهم اکتویتی  List 
را در برنامه با ارسال پوش باز کنم
طبق تصویر ارسالی نوشته 
درسته؟؟
اکتویتی داخل پوشه دیگر نیست

**Comment by mahami064** [comment]
جواب این سوال من چطوری؟؟

**Comment by mahdi-malv** [comment]
<div dir='rtl'>

سلام

این امکان برای فریم‌ورک‌هایی طراحی‌شده که اکتیویتی به صورت نیتیو توسط خود کاربر ساخته میشه و از اسم نهایی توی مانیفست و کامل اطلاع دارن.

توی بیسیک‌۴اندروید کدهای نیتیو جنریت می‌شن و برای اینکه بدونید اسم و پکیج‌نیم اکتیویتی چیه باید کدهای جنریت‌شده رو ببینید.

به طورکلی این امکان برای کد نیتیو طراحی شده و برای فریم‌ورک‌ها خیلی کاربرد خاصی نداره.

</div>

**Comment by mahdi-malv** [comment]
The feature is unsupported for this framework, so the issue will be closed.
Feel free to reopen in case you request for this feature to be added to Plugin.

**Comment by mahami064** [comment]
آخرش
میشه به برنامه ای که با بیسیک ساخته شده
پوشه باز کردذن اکتویتی خاص فرستاد یا نه؟؟
