### ISSUE TITLE
عدم باز نمودن عکس در برنامه

### ISSUE THREAD

**Issue by mahami064** [pusheco/b4a-sample#3]
من طبق تصویر  در مرحله اول و مرحله دوم می خواهم عکس برای برنامه  ام بفرستم
پوش در برنامه دریافت می شود 
ولی عکسی نشان داده نمی شود
![1-2](https://user-images.githubusercontent.com/55809870/65632225-07edae00-dfe6-11e9-9778-d92416225f80.JPG)
![1-3](https://user-images.githubusercontent.com/55809870/65632227-08864480-dfe6-11e9-9c5f-acd7d7268979.JPG)

من برنامه را با بیسیک نوشته ام

**Comment by mahdi-malv** [comment]
<div dir='rtl'>

سلام
عکس بزرگ اینجوره که توی نوتیفیکیشن اضافه‌میشه و باید نوتیفیکیشن رو وقتی نمایش داده‌شده به سمت پایین سوآیپ کنید تا عکس اون هم دیده شه.

این مورد رو هم تست کنید.

اگر نشد با ایمیل کنسول فایل برنامتون رو به پشتیبانی ارسال کنید و با دادن آدرس ایشو، اطلاع بدید که این مورد روی برنامه‌تون تست بشه.

</div>

**Comment by mahdi-malv** [comment]
Inactive for 3 days. Feel free to reopen if this problem still exists.
