### ISSUE TITLE
رنگی کردن متن دریافت در برنامه

### ISSUE THREAD

**Issue by mahami064** [pusheco/b4a-sample#4]
نمیشه متنی که با پوش فرستاده میشه
وقتی در برنامه نمای شداده میشه 
رنگی باشه
؟؟؟

**Comment by mahdi-malv** [comment]
<div dir='rtl'>
سلام.
متاسفانه رنگ متن نوتیفیکیشن در لایبرری قابل تنظیم نیست.
</div>
